[package]
name = "empeaks_rust_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "empeaks_rust_core"
crate-type = ["cdylib"]

[dependencies]
pyo3    = { version = "0.22", features = ["extension-module", "abi3-py311"] }
numpy   = "0.22"
ndarray = "0.16"
lbfgsb-rs-pure  = "0.1.1"
rayon   = "1.10"
roots   = "0.0.8"
xsf     = "0.5.1"


[profile.release]
opt-level = 3
lto = true
